### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by mpkosewski** [gordboy/rtl8812au#1]
Out of curiosity, does this also support packet injection and whatnot as well?

**Comment by gordboy** [comment]
I don't actually know the answer, my friend. All I know is that my TP-Link Archer T4U is working like a champ. The 5.1.5 driver is OK, but has memory leaks and other badness, which 5.2.9 claims to have fixed.

**Comment by mpkosewski** [comment]
No worries. I'll try to check it out tonight. I'm running the Alfa AWUS036ACH and I've been playing with different drivers. My biggest complaint is that it for whatever reason, won't work with mana-toolkit the way it's supposed to, picking up probes and rebroadcasting that wifi. I know it's still new but still, doesn't quite make sense why not. lol good to know about the memory leaks tho! I'll stay away from 5.1.5 :)

**Comment by gordboy** [comment]
OMG I thought I was in for an easy life. Now I am **right down the rabbit hole** with fixes for 4.11 and 4.12 kernels. It all works fine on 4.10 for me, thus far, but I cannot stay there forever.

I can see that I will be adding more VIDs and writing/borrowing/stealing HAL code for other similar devices before long. **Maybe.**

That's after I figure out the cleanup code and the new destructor/freeing convention introduced in 4.11.9 cfg80211 ioctls, which of course has **moved the goalposts entirely**. Then there is **roaming** in 4.12, and the niggling issue of unused flags that have vanished in 4.12 also.

Thank goodness the #include <linux/sched/signal.h>issue introduced in 4.11 is simple. We like simple. **We like simple a lot**. Now get back to work everybody, for **pain is the touchstone of spiritual growth** :)

**Comment by mpkosewski** [comment]
I barely understood what you said haha xD but after work I'll try to set it up and see how it works. I did see in one of the source codes configuring "monitor mode" which is promising but didn't really see anything for "master mode" (I didn't look horribly hard cuz I on my phone lol)
