### ISSUE TITLE
My device is missing in the devices list please add or help me in adding it

### ISSUE THREAD

**Issue by chirag7jain** [gordboy/rtl8812au#10]
Hi

I am using ubuntu 17.10 with linux kernel 4.13.0-12

Earlier I was using drivers from https://github.com/gnab/rtl8812au, it was working upto kernel 4.11 for me but now it doesn't. I think some changes in the kernel affected it.

I currently using this device - https://www.amazon.com/Wireless-Adapter-600Mbps-150Mbps-433Mbps/dp/B074J96YYH

I don't know specifics about this device but given pointers I will be able to find more details.

**Comment by Jinovas** [comment]
Just ran into this issue myself shortly after you when I actually tried using it again. However I am using the alfa AWUS036ACH.

**Comment by stevenskeard** [comment]
Devices can be added by modifying usb_intf.c file located in <repo>/os_dep/linux/usb_intf.c. Assuming you have a device which contains a supported Realtek chipset (eg. 8812A or 8814A). You will see two sections in the file, #ifdef CONFIG_RTL8812A & #ifdef CONFIG_RTL8814A, that have consumer devices in them. You can get the necessary USB ID's by entering 'lsusb' in a terminal and looking for your wifi adapter (eg. Bus 001 Device 005: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter). The important part will be ID <part1>:<part2>. Copy-paste a line in the relevant section (eg.  {USB_DEVICE(0x0409, 0x0408), .driver_info = RTL8812}, /* NEC - */
) and replace the 0x0409 with 0x<part1> and the 0x0408 with 0x<part2>

**Comment by chirag7jain** [comment]
@stevenskeard can you help me add it.

The is the details that I get from lsub about the device
Bus 002 Device 009: ID 0bda:a811 Realtek Semiconductor Corp.

**Comment by chirag7jain** [comment]
I just retried another fork copy of rtl8812 - https://github.com/gnab/rtl8812au

It worked for me with ubuntu - linux kernel 4.13.0-15
