### ISSUE TITLE
ifconfig doesn't see wlan device for my Edimax 7811dac AC600

### ISSUE THREAD

**Issue by Goga777** [gordboy/rtl8812au#13]
I installed your deb package and with modprobe 8812au installed the driver. But with ifconfig -a I can't see my Edimax 7811DAC based on 8811au chipset

uname -a
Linux debian 4.11.0-trunk-amd64 #1 SMP Debian 4.11-1~exp2 (2017-05-05) x86_64 GNU/Linux

[  105.238902] 8812au: loading out-of-tree module taints kernel.
[  105.248625] usbcore: registered new interface driver rtl8812au
[  343.209924] usb 1-2: USB disconnect, device number 2
[  349.445258] usb 1-2: new high-speed USB device number 3 using ehci-pci
[  349.594490] usb 1-2: New USB device found, idVendor=7392, idProduct=a812
[  349.594508] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  349.594516] usb 1-2: Product: Edimax AC600 USB
[  349.594524] usb 1-2: Manufacturer: Realtek
[  349.594531] usb 1-2: SerialNumber: 00e04c000001

ifconfig -a
enp1s0f0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 30:65:ec:05:b0:4e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 26  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2  bytes 100 (100.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 100 (100.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
#it is internal wifi module on my notebook
        inet 192.168.1.64  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 0c:84:dc:0d:6a:17  txqueuelen 1000  (Ethernet)
        RX packets 4553  bytes 2143630 (2.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4078  bytes 2484051 (2.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by gordboy** [comment]
Now see, the problem here is that the driver only supports 8812AU. 8812 and 8811 are not the same. Sorry squire.
