### ISSUE TITLE
rpi support?

### ISSUE THREAD

**Issue by ojnickel** [gordboy/rtl8812au#15]
i have a RPI3 with arch  linux.
How can i compile this driver? I added:
CONFIG_PLATFORM_ARM_RPI =y
CONFIG_PLATFORM_I386_PC= n
to Makefile in a fork (mk-fg) after cloning it.
It did not work there and its the same code with a few minor changes.

Do these changes to Makefile suffice?

**Comment by gordboy** [comment]
I have no idea squire. I only know about x86.

But @dkadioglu might have the answer for you.

https://github.com/dkadioglu/rtl8812au-2/commit/bb4c37a95b14639f2bf1b3efc84fc9983eabd4a1

**Comment by dkadioglu** [comment]
@ojnickel 
With this change (dkadioglu/rtl8812au-2@bb4c37a) the driver builds fine for me. I'm using Arch Linux on a RPi3, too. Is there any error during your build?

**Comment by ojnickel** [comment]
Sorry, i write late...

i did clone his  repo and checkout rpi-build.
But i've got this error:

# make clean && make -j5 && make install && make clean
/bin/sh: bc: command not found
#make -C /lib/modules/4.9.64-1-ARCH/build M=/home/alarm/git/rtl8812au/dkadioiglu clean
cd hal ; rm -fr */*/*/*.mod.c */*/*/*.mod */*/*/*.o */*/*/.*.cmd */*/*/*.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core/efuse ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd platform ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
/bin/sh: bc: command not found
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.9.64-1-ARCH/build M=/home/alarm/git/rtl8812au/dkadioiglu  modules
make[1]: Entering directory '/usr/lib/modules/4.9.64-1-ARCH/build'
/bin/sh: bc: command not found
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_cmd.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_security.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_io.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ioctl_query.o
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c: In function 'dump_drv_version':
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c:50:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                                              ^
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c:50:62: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ioctl_set.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ieee80211.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_mlme.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_mlme_ext.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:293: /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1493: _module_/home/alarm/git/rtl8812au/dkadioiglu] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.9.64-1-ARCH/build'
make: *** [Makefile:1811: modules] Error 2
# make clean && make -j5 && make install && make clean
/bin/sh: bc: command not found
#make -C /lib/modules/4.9.64-1-ARCH/build M=/home/alarm/git/rtl8812au/dkadioiglu clean
cd hal ; rm -fr */*/*/*.mod.c */*/*/*.mod */*/*/*.o */*/*/.*.cmd */*/*/*.ko
cd hal ; rm -fr */*/*.mod.c */*/*.mod */*/*.o */*/.*.cmd */*/*.ko
cd hal ; rm -fr */*.mod.c */*.mod */*.o */.*.cmd */*.ko
cd hal ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core/efuse ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd core ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep/linux ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd os_dep ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
cd platform ; rm -fr *.mod.c *.mod *.o .*.cmd *.ko
rm -fr Module.symvers ; rm -fr Module.markers ; rm -fr modules.order
rm -fr *.mod.c *.mod *.o .*.cmd *.ko *~
rm -fr .tmp_versions
/bin/sh: bc: command not found
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.9.64-1-ARCH/build M=/home/alarm/git/rtl8812au/dkadioiglu  modules
make[1]: Entering directory '/usr/lib/modules/4.9.64-1-ARCH/build'
/bin/sh: bc: command not found
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_cmd.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_security.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_io.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ioctl_query.o
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c: In function 'dump_drv_version':
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c:50:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                                              ^
/home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.c:50:62: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ioctl_set.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_ieee80211.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_mlme.o
  CC [M]  /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_mlme_ext.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:293: /home/alarm/git/rtl8812au/dkadioiglu/core/rtw_debug.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1493: _module_/home/alarm/git/rtl8812au/dkadioiglu] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.9.64-1-ARCH/build'
make: *** [Makefile:1811: modules] Error 2
%

**Comment by gordboy** [comment]
I left a comment here ...

https://github.com/dkadioglu/rtl8812au-2/commit/bb4c37a95b14639f2bf1b3efc84fc9983eabd4a1#commitcomment-25834579
