### ISSUE TITLE
Could you make it support rtl8814au

### ISSUE THREAD

**Issue by zyworkshop** [gordboy/rtl8812au#2]
I have a D-link dwa-192, which runs on driver rtl8814au. Would you add support to it?

**Comment by gordboy** [comment]
I'm afraid it is beyond my ability, squire. There are too many missing HAL files. I dare say someone will address this, in the same way 8821A support was added to other versions, but I am going to stick with 8812A. The only thing I am planning on doing is adding (hopefully simple) fixes for newer kernels, as and when I need them.
