### ISSUE TITLE
New 5.2.9 driver discussion/feedback (not issues)

### ISSUE THREAD

**Issue by MilhouseVH** [gordboy/rtl8812au#3]
Hi @gordboy - hope you don't mind me opening an "issue" which might be useful for more informal/general discussion (as per https://github.com/astsam/rtl8812au/issues/51#issuecomment-315654701) in these early days. Please close if you'd rather discussion take place elsewhere or on a different platform (or once this "issue" has served its purpose).

Regarding the Elecom ID, let's forget that then - I'm not sure why it was originally added (dim & distant past) but I've now dropped from my [gordboy branch](https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:gordboy_rtl8812au) all 3 of the extra IDs we were carrying.

Many thanks for picking up the slack on this driver, it's like the wild west with all these repositories (many of which have too much tumble weed rolling around...!) :)

**Comment by gordboy** [comment]
All good, squire.

Am I right in thinking you are some sort of mcleod (from an email addy i noticed on one of your commits) ? I'm from Edinburgh, Scotland myself.

**Comment by MilhouseVH** [comment]
Yep, parents from Outer Hebrides but I'm from London. :) I do enjoy visiting Edinburgh though - haggis for breakfast is a delight... :)

**Comment by gordboy** [comment]
Now just one thing squire. This driver only supports 8812A, AFAIK because all the HAL stuff is missing for 8821A, 8814A &etc.

My guess is that Realtek have split up the drivers. Until we get proper usernames/passwords for the Realtek FTP site, we will be blundering around in the dark. I am not that keen on writing code, that almost certainly already exists.

So you might have to stick with 5.1.5 for now, simply because it supports more classes of devices.

**Comment by MilhouseVH** [comment]
Unfortunately I don't know how much of an issue the loss of 8821A/8814A will be. Maybe no issue at all - to be honest I'm not at all familiar with the Realtek hardware market and which chipsets are the most popular. Switching to a driver that doesn't support the 8821A and 8814A is a risk, but the feedback on this v5.2.9 driver so far from the 8812AU user is very positive - his AC is working so maybe it's worth the risk...

**Comment by gordboy** [comment]
Cool. 

I've been looking at the whole kodi/libreelec thing. And as a matter of fact, I have another project that I am thinking of resurrecting. 3D spectrum analyzer for OpenGL - http://xspect3d.sourceforge.net/

I was thinking that I could adapt my program to be a visualiser plugin, as well as a standalone app.

I used to run mythtv years ago when dvb-t and dvb-s was all the rage and it was OK but a bit Heath Robinson string and sellotape stuff. Now kodi seems very capable indeed, and it Just Worked (TM) for me.

Anyways, all this excitement getting back out of retirement from coding, has rejuvenated me. I was at Debconf here in Edinburgh 10 years ago, and I even have a Linux Journal article, from way back - http://www.linuxjournal.com/article/5867 

Onwards and Upwards :)

**Comment by MilhouseVH** [comment]
Unfortunately it didn't take long to find users [[1](https://forum.kodi.tv/showthread.php?tid=298461&pid=2619568#pid2619568)],[[2](https://forum.libreelec.tv/thread/6133-rtl8812au-wifi-dongle-on-rpi-3/?postID=56337#post56337)] that would be cut off after switching to this new driver, so I think the risk is too great and LibreELEC will just have to stick with the 5.1.5 driver and broken AC as it does at least support a wider range of devices. I'll continue with the @paspro repo as he seems active again and has merged the outstanding pull requests.

Thanks very much for your efforts - this driver certainly looks more stable than older drivers (for rtl8812au users) so looks to be worth pursuing for those users at least. I'll keep a watch on this repo but ping me if you make any progress on adding support for the other hardware and need anything tested.

All the best!

**Comment by gordboy** [comment]
Thanks bro.

You know, what I'm really hoping is that one of the Young Turks will fork this off and add the HAL stuff for the other chipsets, following the style of the 8812A in 5.2.9. It is not trivial, as a lot of it is undocumented low-level registers, but at least there are previous drivers to crib from.

My current challenge is to get back to spectrum analyzers. Take care squire.

**Comment by MilhouseVH** [comment]
Oh god no... not another fork! This rtl community really does need to start working together! :)
