### ISSUE TITLE
iwconfig wlan0 mode monitor gives error

### ISSUE THREAD

**Issue by oguzhantopcu** [gordboy/rtl8812au#3]
root@javier-f22:~/temp# ifconfig wlx00c0ca960c26 down
root@javier-f22:~/temp# iwconfig wlx00c0ca960c26 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlx00c0ca960c26 ; Invalid argument.

The things I did is simply installing driver from this repository.

What could be wrong?

**Comment by gordboy** [comment]
This driver does not support monitor mode, is the short answer.
