### ISSUE TITLE
monitor mode causes freeze

### ISSUE THREAD

**Issue by werdjockey** [gordboy/rtl8812au#4]
Hello, I am not a programmer, and I really appreciate all of your work.

I am currently on
uname -r 
4.12.0-041200-generic
 My issue is that if I enter the command 'iwconfig wlan0 mode monitor' my laptop freezes and becomes completely unresponsive to where I have to shut it down by holding the power button. Please let me know if you need any further information and I will do my best to supply it.

**Comment by gordboy** [comment]
Hi @werdjockey I think the problem is related to the fact that this driver does not support monitor mode. I have no plans to include monitor mode, nor support any other chipset than 8812AU. You might try using one of the 5.1.5 drivers.
