### ISSUE TITLE
the connection is not really stable

### ISSUE THREAD

**Issue by yangxuan8282** [gordboy/rtl8812au#8]
My devices is an ASUS USB-AC56 adapter, after install this driver the connection seems not really stable, when use as an AP or STA(client) with 5G band the connection will disconnect every few minutes, and I also got same issues when use other drivers. I'm not sure this is normal for rtl8812au devices.

**Comment by codesport** [comment]
@yangxuan8282 would you try https://github.com/xxNull-lsk/rtl8812AU/tree/v5.2.9 and report back on what you find.

**Comment by gordboy** [comment]
So here's the thing. One of the main problems with these devices is overheating. Both of the device and the USB port, especially if it is USB 2. Not so much of a problem with 2GHz band but very much a problem in 5GHz band.

Simply plugging the device (mine is a TP Link Archer T4U) into another port, preferably well away from the last one, is enough to cool it down for a while.

Of course the driver from Realtek may be faulty as well, but I have no plans to test this extensively. It works acceptably for me, and that, my friend, is good enough.

Best wishes.
