### ISSUE TITLE
Realtek v5.2.9_22809.20170621 

### ISSUE THREAD

**Issue by codesport** [gordboy/rtl8812au#9]
@gordboy is there anyway that your and this version (https://github.com/xxNull-lsk/rtl8812AU/tree/v5.2.9) can be merged? That 5.2.9 branch was created by [**@smitgd**](https://github.com/xxNull-lsk/rtl8812AU/pull/9)

Combining both your brainpower and fixes into one branch would make both of these better drivers.  Plus, there's no use in replicating the same project with the same functionalities!

**Comment by gordboy** [comment]
I wish everyone the best of luck, and they are free to fork and pilfer anything I have here. I did the same ruthlessly with other peoples' contributions, especially from the 5.1.5 driver.

But really, I'm not that interested in Monitor Mode, so the only changes I plan on making, are fixes for new kernels, as and when they are needed. As of now, the driver works for everything up to and including 4.14 RC1.
